components/content/LineLink.vue
content/voies-lyonnaises/ligne-1.md
content/voies-lyonnaises/ligne-10.md
content/voies-lyonnaises/ligne-11.md
content/voies-lyonnaises/ligne-2.md
content/voies-lyonnaises/ligne-5.md
content/voies-lyonnaises/ligne-8.md
content/voies-lyonnaises/ligne-9.md

Bonjour
De nombreuses pages décrivant les voies lyonnaises mentionnent des intersection avec d'autres voies.
Ce commit introduit un nouveau composant `LineLink` qui peut être utilisé inline dans le contenu des markdowns afin d'obtenir des liens de la couleur de la ligne ciblée.
```md
[Voie Lyonnaise 8](https://cyclopolis.fr/voie-lyonnaise-8) du boulevard du Valvert à l'avenue Victor Hugo
```
```md
:line-link{line=8} du boulevard du Valvert à l'avenue Victor Hugo
```

feat(content) add and use LineLink inline component

---

content/compteurs/pont-de-la-mulatiere.json
content/compteurs/quai-augagneur.json
content/compteurs/tunnel-croix-rousse.json
pages/compteurs/[slug].vue

Bonsoir
Cet ajout permet de lister les Voies Lyonnaises sur lesquelles est placé un compteur.
Voici ce que ça rend pour le compteur à la sortie du tunnel de la Croix Rousse :

feat(content): list lines on counters pages

---

pages/compteurs/index.vue

Bonjour
Voici une proposition ajoutant la possibilité de trier les compteurs :

feat(counters): add sorting options on main page

---

components/chart/MonthComparison.vue
components/chart/TotalByYear.vue

Bonjour
Cette PR poursuit ce qui a été fait avec l'ajout de badges roses "record" sur les compteurs de la page principale.
Sur les columns charts, la valeur maximale est désormais elle aussi en rose ce qui facilite le coup d’œil pour trouver quelle année à le record de passage lorsque les résultats sont serrés, comme par exemple sur septembre pour le pont Lafayette :

feat(charts): highlight max values in lvv-pink

---

components/content/LineLink.vue
content/voies-lyonnaises/ligne-1.md
content/voies-lyonnaises/ligne-2.md

Bonjour
`line-link` accepte désormais un paramètre `anchor` optionnel. C'est plus pratique depuis que les ancres ont été ajoutées aux headings.
J'ai ajouté deux exemples d'utilisation dans cette PR. Ajuster les autres liens sur les pages des VL ou des News pourra etre fait au fil de l'eau dans des PR futures.
Exemple VL1 vers VL2
```md
Cette section est en tronçon commun avec la :line-link{line=2 anchor="boulevard-stalingrad-nord"}.
```

feat: add optional anchor param for line-link

---

composables/useMap.ts
pages/evolution/index.vue

Bonjour, cette PR pour apporter quelques corrections mineures à la carte d'évolution du réseau cyclable.
Une incohérence apparaissait lorsque l'on désélectionnait toutes les options de la toolbar en bas de la page : le compteur indique bien 0km construits, mais les tracés de la dernière année sélectionnée apparaissent toujours.
Une condition empêchait la mise à jour de la carte dans le cas où l'on n'avait plus de tracés.
Également une correction du nombre de colonnes affichées dans la grille de cette toolbar pour qu'elle prenne toute la longueur de la fenêtre, et ainsi obtenir le résultat suivant.
Au passage, merci pour votre travail sur ce fabuleux outil, que je découvre à peine !

Evolution map enhancements

---

components/content/ContentImage.vue
components/content/StreetViewLink.vue
content/voies-lyonnaises/ligne-1.md
content/voies-lyonnaises/ligne-3.md
content/voies-lyonnaises/ligne-7.md

Bonjour
On en avait parlé brièvement ensemble, je pense qu'on est tous assez friand de l'effet "avant / après" en photo pour rendre les évolutions du réseau plus tangible.
Ainsi je vous propose l'ajout de liens vers Google Street View. Il ne s'agit pas d'une intégration poussée où une iframe serait directement intégrée au site, car cela nous ferait entrer sur le terrain des API keys, des quotas, des personnes qui ne souhaitent pas se faire tracker par big G…
Ici la solution est plus pragmatique. Il suffit d'ajouter un nouveau paramètre facultatif `streetView` en plus de la légende des photos au sein des pages.
J'ai fait 3 exemples dans cette PR. Si je prends le cas de la VL3 (Quai d'Arloing), voila comment ça marche: 
```
:content-image
---
imageUrl: …
```

feat: add StreetViewLink component

---

components/LegendModal.vue
components/Map.vue
composables/useMap.ts

Bonjour
Cette PR apporte la possibilité d'afficher ou masquer les différents type de sections de VL depuis la légende.
Des captures d'écran pour commencer: 
Uniquement les sections en travaux:
Sections terminées et reportées:
Pour de futures PRs, il y a encore du boulot pour rendre l'UX plus sympa:
- comme indiqué par Thibaut, ce bouton "Légende" pourrait se renommer en "Layers" avec un icone différent du "i" actuel.
- les cases à cocher méritent certainement d’être stylées (blue LVV…).
- avoir cette modal en plein milieu de l'écran masque un peu ce qu'on est en train de faire lorsqu'on coche et décoche les cases (surtout en faible zoom), donc il faudrait peut être que ça devienne un panneau latéral rétractable à souhait.
- au sein de cette légende on pourrait bien entendu ajouter …

feat(map): add sections toggles in legend

---

components/FilterModal.vue
components/LegendModal.vue
components/Map.vue
maplibre/FilterControl.ts
maplibre/filter.svg
pages/compteurs/velo/[slug].vue
pages/compteurs/velo/index.vue
pages/compteurs/voiture/[slug].vue
pages/compteurs/voiture/index.vue

Je souhaite sortir les filtres de la légende, car il s'agit de 2 choses différentes.
Concrètement, ça prendrait la forme d'un bouton directement intégré dans la carte.
Il faut changer l'icone, par un icone de filtre, mais ça ressemblerait à ça

feat(carto): ajout d'un bouton pour gérer les filtres

---

content/voies-cyclables/ligne-1.md

Bonsoir
La VL1 est un peu l'épine dorsale du réseau. De part sa nature nord<->sud, elle permet de s'interconnecter avec une grande partie du réseau.
Dans cette PR, c'est cet atout que j'ai voulu mettre en avant, en mentionnant les lignes ouest<->est qui croisent son chemin.
Cela permet aux lecteurs de plus facilement se balader naturellement de page en pages, et potentiellement de mieux distribuer le jus SEO.

feat: add line-links from vl1

---

pages/tableau-de-bord/index.vue

* Masque "Fréquentation max" si `voie.trafic` n'est pas défini (#415)
* Remplace "Voies Lyonnaises" par `revName.plural`

Tableau de bord : changements mineurs

---

content/voies-cyclables/ligne-2.json

Le tunnel Vivier Merle a été fermé pour commencer les travaux pour le passage de la VL2.  J'ai pu voir le tweet de Lyon a vélo sur la section nord du tunnel également : https://x.com/LyonAVelo/status/1842145374795862329

Passage en travaux de la section Tunnel Part Dieu

---

components/home/StatSection.vue
composables/useConfig.ts
composables/useMap.ts
config.json

Rebonjour,
Petite PR pour corriger le nombre de voies.
Il est actuellement hardcodé à 2 endroits (page d'accueil + affichage des postplanned sur la carte).
Je propose de créer une variable de configuration pour la gérer (à 12 par défaut).
On pourrait aussi compter le nombre de fichiers de content/voies-cyclables/*.json mais j'ai peur que des effets de bord puissent apparaître.
Aucun
Changement à appliquer sur les forks.

Nombre de voies hardcodé

---

components/content/ContentImage.vue

Quand on ajoute une image dans un markdown : possibilité de lui passer un `link` qui permet de rediriger vers ce lien quand on clique sur l'image.
Exemple : 
```
::content-image
---
imageUrl: https://cyclopolis.lavilleavelo.org/vl1/croix-luizet.jpeg
link: https://google.fr
caption: Aperçu de la Voie Lyonnaise 1 franchissant le canal de Jonage (Villeurbanne)
credit: SYTRAL Mobilités
streetView: 45.7832245,4.8937612,3a,75y,259.87h,90t
---
::
```

feat(content): image markdown clickable avec redirection

---

content/compteurs/velo/cours-vitton-sncf.json
content/compteurs/velo/passerelle-de-la-paix.json

Bonjour
Cette PR ajouter deux nouveaux compteurs dans le 6ème arrondissement.
- Passerelle de la Paix
- Cours Vitton pont SNCF
Les données sont à jour, Novembre 2024 est bien inclus.
Merci à Audrey pour la notif: https://github.com/benoitdemaegdt/voieslyonnaises/issues/486

feat(counters): add Passerelle de la Paix and Cours Vitton

---

components/app/Footer.vue

Petite PR pour:
- supprimer l'icone et lien vers X
- ajout de Bluesky et mastodon
- ajout de github

Supprime icônes X et remplace par Bsky et Masto

---

helpers/helpers.ts
pages/compteurs/velo/index.vue
pages/compteurs/voiture/index.vue

Bonjour
Avec ce changement, l'utilisateur peut désormais filtrer les compteurs vélo et voitures par arrondissement / commune: `Lyon 4`, `Bron`…
Réference: https://github.com/benoitdemaegdt/voieslyonnaises/issues/485

feat: include arrondissement field in counters filter

---

assets/icons/satisfactory.svg
assets/icons/unsatisfactory.svg
components/StatsQuality.vue
components/content/Overview.vue
components/content/QualityText.vue
components/tooltips/LineTooltip.vue
composables/useConfig.ts
composables/useStats.ts
config.json
pages/index.vue
types/index.ts

Bonjour,
Dans le but de faire avancer la gestion des forks, j'ai commencé à intégrer la notion de qualité en m'inspirant de ce que Montpellier a fait. 
Le but n'est évidemment pas de forcer tout le monde à afficher/gérer une notion de qualité par tronçon.
Au contraire, cette fonctionnalité est désactivée par défaut. Elle n'a donc aucun impact sur le site lyonnais.
Dans config.json, il faudra ajouter `"qualityDisplay": true` pour activer la fonctionnalité.
Enfin, aucune information n'est affichée si aucun élément n'est défini (y compris si la fonctionnalité est activée)
J'ai ajouté un composant QualityText qui permet d'ajouter un texte simple  : 
```
:qualityText{type="perfect"} *via Tunnel mode doux et avenue Duquesne*
``` 
Pour la carte interactive, ajouter la property _quality_  permet …

Ajout de la qualité (tooltip et composant texte)

---

package-lock.json
package.json
server/routes/sitemap.xml.ts

I've tested it locally, comparing the generated XML between 7.x and 8.x : they are identical.
closing #371

chore(deps): bump sitemap to 8.x

---

components/ContentFrame.vue
pages/compteurs/comparaison/[slug].vue
pages/compteurs/velo/[slug].vue
pages/compteurs/voiture/[slug].vue

Salut
L'arrondissement ou la commune des compteurs vélo et voiture est affiché sur chaque card lorsqu'on est sur la grille qui les liste tous, mais bizarrement on avait omis d'indiquer cette mème information sur les pages individuelles.
Example:

feat(counter): display arrondissement as subTitle
