lavilleavelo/cyclopolis

components/Header.vue
mieux comme ça non ? :p 
super projet en tout cas
=> fix header typo

composables/useTooltip.ts, content/voies-lyonnaises/ligne-11.json, content/voies-lyonnaises/ligne-11.md, content/voies-lyonnaises/ligne-12.md, content/voies-lyonnaises/ligne-5.md, content/voies-lyonnaises/ligne-6.md, content/voies-lyonnaises/ligne-7.md, content/voies-lyonnaises/ligne-9.md
Ajout des images manquantes
Ajout des distances dans le tooltip
=> Ajout des images manquantes

components/app/Footer.vue
Que pensez-vous de rajouter Linkedin et Instagram (maintenant qu'il y a de l'activité sur ces réseaux, merci Clémence)...par contre, il y a aussi un compte youtube mais rien depuis 3 ans https://www.youtube.com/channel/UCGoCpNNf4LXeBhagGzclP8g
=> Linkedin et instagram ?

components/ContentFrame.vue, components/NewsBanner.vue, content/news/2023-10-02.md, content/news/2023-10-09.md, content/news/2023-10-16.md, content/news/2023-11-03.md, pages/[_slug]/index.vue, pages/historique.vue
=> Gestion markdown de l'historique

components/Map.vue, composables/useMap.ts, composables/useTooltip.ts, content/voies-lyonnaises/ligne-1.json, content/voies-lyonnaises/ligne-10.json, content/voies-lyonnaises/ligne-11.json, content/voies-lyonnaises/ligne-12.json, content/voies-lyonnaises/ligne-2.json, content/voies-lyonnaises/ligne-3.json, content/voies-lyonnaises/ligne-4.json, content/voies-lyonnaises/ligne-5.json, content/voies-lyonnaises/ligne-5.md, content/voies-lyonnaises/ligne-6.json, content/voies-lyonnaises/ligne-6.md, content/voies-lyonnaises/ligne-7.json, content/voies-lyonnaises/ligne-8.json, content/voies-lyonnaises/ligne-9.json, pages/compteurs/index.vue
=> refonte page principale des compteurs

.eslintrc, composables/useMap.ts, composables/useTooltip.ts, pages/compteurs/[slug].vue, pages/compteurs/index.vue
-> sort par par fréquentation décroissante
-> ajout d'une search bar
=> Compteurs : Ajout d'une barre de recherche

composables/useMap.ts, pages/evolution/index.vue
Je drop le slider pour utiliser des tuiles, une par année.
=> Amélioration de la carte évolutive

content/voies-lyonnaises/ligne-10.json, content/voies-lyonnaises/ligne-4.json, content/voies-lyonnaises/ligne-5.json
=> correction de la date de fin des travaux sur le pont clemenceau

components/LegendModal.vue, components/Map.vue, components/content/Overview.vue, composables/useMap.ts, pages/[_slug]/carte.vue, pages/carte-interactive/embed.vue, pages/carte-interactive/index.vue
=> Feat hover

components/Map.vue, pages/carte-interactive/index.vue
Ajout de la geolocalisation, uniquement sur la carte intéractive
=> Test : Ajout de la geolocalisation

content/blog/methodo.md, pages/mentions-legales/index.vue
ça donne ça sur les mentions et la page méthodo du blog. Qu'en pensez-vous ?
=> Ajout de l'obligation de mettre un lien vers cyclopolis et lvv.org

content/voies-lyonnaises/ligne-5.json
Petite erreur cassant le health check action
=> fix anchor

content/voies-lyonnaises/ligne-5.json
C'est bien ça que tu as changé @ThibautChd  ? Si oui, plus qu'à merger
=> Fix mauvais lien

components/ProgressBar.vue, components/Stats.vue, components/content/Overview.vue, composables/useStats.ts, content/voies-lyonnaises/ligne-1.md, content/voies-lyonnaises/ligne-10.md, content/voies-lyonnaises/ligne-11.md, content/voies-lyonnaises/ligne-12.md, content/voies-lyonnaises/ligne-2.md, content/voies-lyonnaises/ligne-3.md, content/voies-lyonnaises/ligne-4.md, content/voies-lyonnaises/ligne-5.md, content/voies-lyonnaises/ligne-6.md, content/voies-lyonnaises/ligne-7.md, content/voies-lyonnaises/ligne-8.md, content/voies-lyonnaises/ligne-9.md
Bonjour
Cette PR ouvre le bal concernant l'idée de tableau de bord décrite ici : https://github.com/benoitdemaegdt/voieslyonnaises/issues/225
A défaut de construire une page complète, elle ajouter les premières pièces du puzzle.
Voici ce que cela donne.
**Avant:**
**Après:**
Bien entendu, il reste pas mal de petits ajustements à régler suivants les voies lyonnaises.
Benoit, pas de soucis pour que tu poursuives cette PR en y faisant la magie dont tu as le secret ;)
=> feat: improve Overview component

components/Map.vue, composables/useMap.ts
Bonjour
Cette PR donne plus d'importance au top 10 compteurs sur la carte, tel que décrit par Thibaut dans : 
> dans chacun des écrans, les dix compteurs qui totalisent le plus grand trafic sont affiché 50% plus gros que les autres, avec un contour blanc épais.
Pour répondre à https://github.com/benoitdemaegdt/voieslyonnaises/issues/251
Voici ce que ça donne à différents niveaux de zoom : 
Le cœur du réglage se situe ici : 
```js
// top counters are bigger and drawn above others
const top = 10;
c.properties.circleSortKey = i < top ? 1 : 0;
c.properties.circleRadius = i < top ? 10 : 7;
c.properties.circleStrokeWidth = i < top ? 3 : 0;
return c;
```
En implémentant tout ça, c'est à dire en touchant plus en profondeur au code de la carte, je me suis rendu compte qu'il y avait un bug en prod. …
=> feat(map): add bigger size for top 10 counters

components/Map.vue, composables/useColors.ts, composables/useMap.ts, package-lock.json, package.json
Il y a du breaking change.
ça ne passe pas pour les loadImages. il faut passer par une promesse plutot que par une callback d'après le changelog.
Pour le reste ça semble ok
=> Montée de version de Maplibre

pages/evolution/index.vue
Salut
Les premières livraisons de kilomètres de VLs pour cette nouvelle année ne vont certainement pas trainer à pointer le bout de leur nez. Autant se tenir prêt.
=> feat(evolution): add 2025 button

components/app/Footer.vue, content/sites-partenaires/paris.md, pages/sites-partenaires/index.vue
Page "Sites partenaires" basé sur la maquette https://github.com/benoitdemaegdt/voieslyonnaises/issues/351#issuecomment-2090407967
Le contenu s'ajoute via fichiers markdown :
=> Sites partenaires

content/voies-cyclables/ligne-1.json, content/voies-cyclables/ligne-2.json, content/voies-cyclables/ligne-5.json, content/voies-cyclables/ligne-7.json
Bonjour,
Suite message de Frédérique Bienvenue, passage en wip du tronçon Transbordeur Nord sur les json des VL1, VL2 et VL5.
=> wip Transvordeur Nord VL1 / VL2 / VL5

components/Map.vue
Salut
Voici une première proposition pour l'affichage kilomètrique de https://github.com/lavilleavelo/cyclopolis/issues/660.
On pourra ajuster le style dans une prochaine PR si besoin.
=> feat(map): display filtered distance

content/voies-cyclables/ligne-7.json
Rilleux section Loup pendu wip > Done.
Source : observation terrain personnelle.
=> Update ligne-7.json Loup Pendu done

components/FilterModal.vue, components/Map.vue, components/filter/FilterButton.vue, components/filter/FilterSection.vue, pages/carte-interactive/index.vue, pages/evolution/index.vue, types/index.ts
- Ajout d'un filtre pour sélectionner les voies lyonnaises sur la carte ;
- Ajout de boutons pour sélectionner/désélectionner les filtres ;
- Les filtres sont ajoutés dans l'URL de la page ;
=> feat: Add "voie lyonnaise" filter
